# Generated by Django 3.0.5 on 2020-04-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('mode', models.IntegerField(choices=[(0, 'Bug'), (1, 'Improvement'), (2, 'New feature')], verbose_name='type')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('barman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvement_submitted', to=settings.AUTH_USER_MODEL, verbose_name='barman')),
            ],
            options={
                'verbose_name': 'improvement',
                'verbose_name_plural': 'improvements',
            },
        ),
    ]
